Lesson 2
js-tasks-ru/js-20210309-2_shambazov pull request #2
Opened 2021-03-13 17:46 UTC by slv177

I think I ve done it.

2021-03-13 17:46 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 02-javascript-data-types/3-omit/index.spec.js — добавлен
```

2021-03-14 14:22 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    result.reverse();
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2021-03-14 14:22 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +  let result = {};
проверьте, тут точно `let`?

2021-03-14 14:25 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +  let result = {};
проверьте точно ли тут `let`?

2021-03-14 14:25 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-03-14 17:03 UTC, slv177 commented on 02-javascript-data-types/1-sort-strings/index.js
> +    result.reverse();
Исправлено. В зависимости от параметра функции происходит сравнение в прямом или обратном порядке.

2021-03-14 17:03 UTC, slv177 commented on 02-javascript-data-types/2-pick/index.js
> +  let result = {};
Заменено на const.

2021-03-14 17:03 UTC, slv177 commented on 02-javascript-data-types/3-omit/index.js
> +  let result = {};
Заменено на const.

2021-03-14 17:04 UTC, slv177 commented
Исправил ваши замечания.

2021-03-16 20:21 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return a.localeCompare(b, ["ru-ru-u-kf-upper"], {sensitivity: "case"});
подумайте, может есть способ избавиться теперь уже от повторяющегося кода?

2021-03-16 20:22 UTC, dosandk commented on 02-javascript-data-types/3-omit/README.md
> + apple: 2,
этих изменений не должно быть в PR

2021-03-16 20:22 UTC, dosandk requested changes
нужно избавиться от повторяющегося кода в решении sortStrings

2021-03-17 08:23 UTC, slv177 commented on 02-javascript-data-types/3-omit/README.md
> + apple: 2,
 Кажется, удалил.

2021-03-19 14:17 UTC, dosandk commented on 02-javascript-data-types/3-omit/README.md
> +# omit
этих изменений не должно быть в PR

2021-03-19 14:17 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +      return b.localeCompare(a, ["ru-ru-u-kf-upper"], {sensitivity: "case"});
подумайте, можно ли избавиться от дубликатов кода в строках 13 и 15

2021-03-19 14:18 UTC, dosandk approved these changes

2021-03-19 14:18 UTC, merged