Задания второго урока
js-tasks-ru/js-20210309-2_shambazov pull request #3
Opened 2021-03-20 20:12 UTC by slv177

Тесты проходят, поэтому формально можно показать вам.

Видимо, можно как то избавиться в нескольких заданиях от конструкции:
  if (size === undefined) {
    return string;
  }
но еще не понял как. 

Самое сложное задание было 1 - было непонятно, как обратиться к объекту, которого в момент создания функции еще нет, но методом тыка нашел. Метод прохода по ключам, признаюсь, подсмотрел в интернете, но честно с ним разобрался.

2021-03-20 20:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2021-03-22 09:56 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  let keys = path.split('.');
good 👍

2021-03-22 09:56 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  let keys = path.split('.');
проверьте, здесь точно `let`?

2021-03-22 09:57 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +    if(keys.length == 0) return undefined;
1. нет оператора `==` в JS, только `===`
2. мы не работаем с `undefined` напрямую, достаточно просто `return`

2021-03-22 09:57 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2021-03-22 09:58 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +export function trimSymbols(string, size) {
good 👍

2021-03-22 09:58 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
> +    return undefined;
просто `return`

2021-03-23 09:09 UTC, dosandk approved these changes
good 👍

2021-03-23 09:10 UTC, merged